### ISSUE TITLE
KiCAD stable version

### ISSUE THREAD

**Issue by metropt** [mebs/CM4-NAS#1]
Hi,

Any reason not to use KiCAD current stable version?

**Comment by mebs** [comment]
Hi there,
The design started with the official Raspberry Pi CM4 IO board KiCAD project, from which I took some assets and to which I was going back for reference as I was working on this.  For some reason the official design was made with the nightly version of KiCAD (kicad_pro format) so I was stuck with that.
Now that this project is getting a bit of attention, I should do some cleanup but I don't think I would be able to go back to a format that's supported by the stable release.

Official IO board design available on their website: https://www.raspberrypi.org/products/compute-module-4-io-board/?resellerType=home

**Comment by metropt** [comment]
I saw on the KiCAD forum that there is no reason tu use a night build version of KiCAD to design the board. Since there is already some work on port footprints and symbols to current stable KiCAD version I'll try to port your project to this version.

**Comment by mebs** [comment]
I experienced many crashes with the nightly build. Often systematic and easy to reproduce ones that I don't expect to see in a stable release, so if the port is possible I'd definitely appreciate the contribution!
Leaving the issue open until we're fixed on this.

**Comment by mebs** [comment]
Closing this out of lack of activity. I am not planning on porting this project to stable version myself as there would be little to no benefits.
