### ISSUE TITLE
Ethernet MagJack should be changed

### ISSUE THREAD

**Issue by mebs** [mebs/CM4-NAS#17]
The current ethernet jack the board expects is this one: https://www.digikey.ca/en/products/detail/bel-fuse-inc/0826-1G1T-43-F/2107992

There are a couple issues with it:
- It's expensive (costs more than a PCB)
- It's not available on LCSC and certainly not for PCB assembly on JLC

Should be changed for another ethernet jack with magnetics that would be cheaper and available for PCB assembly.

**Comment by terramande** [comment]
hey mebs,

I changed the MagJack, if you like to view, and I also did some minor changes to the length of some traces

**Comment by mebs** [comment]
> hey mebs,
> 
> I changed the MagJack, if you like to view, and I also did some minor changes to the length of some traces

Thank you @terramande! Did you do that through a pull request? I don't see any.

**Comment by terramande** [comment]
> > hey mebs,
> > I changed the MagJack, if you like to view, and I also did some minor changes to the length of some traces
> 
> Thank you @terramande! Did you do that through a pull request? I don't see any.

no don't know how and I ask if you interested ;-)

**Comment by terramande** [comment]
i made a fork, I don't know how to make a pull request :-)
